// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmWm2yOYwxDC_wH8OGj8hG6JWOjTxyfUU',
    appId: '1:320584102047:android:2f3abc052b230fdfa332aa',
    messagingSenderId: '320584102047',
    projectId: 'instagram-clone-kylsnchz-fa35b',
    storageBucket: 'instagram-clone-kylsnchz-fa35b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGxl5KGw5VuraevOvYudljPRE4YrnJMdQ',
    appId: '1:320584102047:ios:1a795d4168b4e773a332aa',
    messagingSenderId: '320584102047',
    projectId: 'instagram-clone-kylsnchz-fa35b',
    storageBucket: 'instagram-clone-kylsnchz-fa35b.appspot.com',
    iosClientId: '320584102047-j66a9spdu5bhbb8q5nstq3n774ravovu.apps.googleusercontent.com',
    iosBundleId: 'com.example.indagram',
  );
}
